/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as AuthenticatedPerfilIndexRouteImport } from './routes/_authenticated/perfil/index'
import { Route as AuthenticatedInteligenciaIndexRouteImport } from './routes/_authenticated/inteligencia/index'
import { Route as AuthenticatedIaIndexRouteImport } from './routes/_authenticated/ia/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedSocWazuhRouteImport } from './routes/_authenticated/soc/wazuh'
import { Route as AuthenticatedSocVelociraptorRouteImport } from './routes/_authenticated/soc/velociraptor'
import { Route as AuthenticatedSocThehiveRouteImport } from './routes/_authenticated/soc/thehive'
import { Route as AuthenticatedSocOpenvasRouteImport } from './routes/_authenticated/soc/openvas'
import { Route as AuthenticatedSocNessusRouteImport } from './routes/_authenticated/soc/nessus'
import { Route as AuthenticatedInteligenciaThreatRouteImport } from './routes/_authenticated/inteligencia/threat'
import { Route as AuthenticatedInteligenciaApisRouteImport } from './routes/_authenticated/inteligencia/apis'
import { Route as AuthenticatedIncidentesTimelineRouteImport } from './routes/_authenticated/incidentes/timeline'
import { Route as AuthenticatedIncidentesPlaybooksRouteImport } from './routes/_authenticated/incidentes/playbooks'
import { Route as AuthenticatedIncidentesCasosRouteImport } from './routes/_authenticated/incidentes/casos'
import { Route as AuthenticatedHerramientasIocRouteImport } from './routes/_authenticated/herramientas/ioc'
import { Route as AuthenticatedHerramientasEmailRouteImport } from './routes/_authenticated/herramientas/email'
import { Route as AuthenticatedHerramientasArchivosRouteImport } from './routes/_authenticated/herramientas/archivos'
import { Route as AuthenticatedConfigUsuariosRouteImport } from './routes/_authenticated/config/usuarios'
import { Route as AuthenticatedConfigPlatformsRouteImport } from './routes/_authenticated/config/platforms'
import { Route as AuthenticatedConfigIaRouteImport } from './routes/_authenticated/config/ia'
import { Route as AuthenticatedConfigAuditoriaRouteImport } from './routes/_authenticated/config/auditoria'
import { Route as AuthenticatedConfigApikeysRouteImport } from './routes/_authenticated/config/apikeys'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilIndexRoute =
  AuthenticatedPerfilIndexRouteImport.update({
    id: '/perfil/',
    path: '/perfil/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInteligenciaIndexRoute =
  AuthenticatedInteligenciaIndexRouteImport.update({
    id: '/inteligencia/',
    path: '/inteligencia/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIaIndexRoute = AuthenticatedIaIndexRouteImport.update({
  id: '/ia/',
  path: '/ia/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSocWazuhRoute = AuthenticatedSocWazuhRouteImport.update({
  id: '/soc/wazuh',
  path: '/soc/wazuh',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSocVelociraptorRoute =
  AuthenticatedSocVelociraptorRouteImport.update({
    id: '/soc/velociraptor',
    path: '/soc/velociraptor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSocThehiveRoute = AuthenticatedSocThehiveRouteImport.update({
  id: '/soc/thehive',
  path: '/soc/thehive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSocOpenvasRoute = AuthenticatedSocOpenvasRouteImport.update({
  id: '/soc/openvas',
  path: '/soc/openvas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSocNessusRoute = AuthenticatedSocNessusRouteImport.update({
  id: '/soc/nessus',
  path: '/soc/nessus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInteligenciaThreatRoute =
  AuthenticatedInteligenciaThreatRouteImport.update({
    id: '/inteligencia/threat',
    path: '/inteligencia/threat',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInteligenciaApisRoute =
  AuthenticatedInteligenciaApisRouteImport.update({
    id: '/inteligencia/apis',
    path: '/inteligencia/apis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIncidentesTimelineRoute =
  AuthenticatedIncidentesTimelineRouteImport.update({
    id: '/incidentes/timeline',
    path: '/incidentes/timeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIncidentesPlaybooksRoute =
  AuthenticatedIncidentesPlaybooksRouteImport.update({
    id: '/incidentes/playbooks',
    path: '/incidentes/playbooks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIncidentesCasosRoute =
  AuthenticatedIncidentesCasosRouteImport.update({
    id: '/incidentes/casos',
    path: '/incidentes/casos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHerramientasIocRoute =
  AuthenticatedHerramientasIocRouteImport.update({
    id: '/herramientas/ioc',
    path: '/herramientas/ioc',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHerramientasEmailRoute =
  AuthenticatedHerramientasEmailRouteImport.update({
    id: '/herramientas/email',
    path: '/herramientas/email',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHerramientasArchivosRoute =
  AuthenticatedHerramientasArchivosRouteImport.update({
    id: '/herramientas/archivos',
    path: '/herramientas/archivos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigUsuariosRoute =
  AuthenticatedConfigUsuariosRouteImport.update({
    id: '/config/usuarios',
    path: '/config/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigPlatformsRoute =
  AuthenticatedConfigPlatformsRouteImport.update({
    id: '/config/platforms',
    path: '/config/platforms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigIaRoute = AuthenticatedConfigIaRouteImport.update({
  id: '/config/ia',
  path: '/config/ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfigAuditoriaRoute =
  AuthenticatedConfigAuditoriaRouteImport.update({
    id: '/config/auditoria',
    path: '/config/auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigApikeysRoute =
  AuthenticatedConfigApikeysRouteImport.update({
    id: '/config/apikeys',
    path: '/config/apikeys',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/config/apikeys': typeof AuthenticatedConfigApikeysRoute
  '/config/auditoria': typeof AuthenticatedConfigAuditoriaRoute
  '/config/ia': typeof AuthenticatedConfigIaRoute
  '/config/platforms': typeof AuthenticatedConfigPlatformsRoute
  '/config/usuarios': typeof AuthenticatedConfigUsuariosRoute
  '/herramientas/archivos': typeof AuthenticatedHerramientasArchivosRoute
  '/herramientas/email': typeof AuthenticatedHerramientasEmailRoute
  '/herramientas/ioc': typeof AuthenticatedHerramientasIocRoute
  '/incidentes/casos': typeof AuthenticatedIncidentesCasosRoute
  '/incidentes/playbooks': typeof AuthenticatedIncidentesPlaybooksRoute
  '/incidentes/timeline': typeof AuthenticatedIncidentesTimelineRoute
  '/inteligencia/apis': typeof AuthenticatedInteligenciaApisRoute
  '/inteligencia/threat': typeof AuthenticatedInteligenciaThreatRoute
  '/soc/nessus': typeof AuthenticatedSocNessusRoute
  '/soc/openvas': typeof AuthenticatedSocOpenvasRoute
  '/soc/thehive': typeof AuthenticatedSocThehiveRoute
  '/soc/velociraptor': typeof AuthenticatedSocVelociraptorRoute
  '/soc/wazuh': typeof AuthenticatedSocWazuhRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/ia/': typeof AuthenticatedIaIndexRoute
  '/inteligencia/': typeof AuthenticatedInteligenciaIndexRoute
  '/perfil/': typeof AuthenticatedPerfilIndexRoute
}
export interface FileRoutesByTo {
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/config/apikeys': typeof AuthenticatedConfigApikeysRoute
  '/config/auditoria': typeof AuthenticatedConfigAuditoriaRoute
  '/config/ia': typeof AuthenticatedConfigIaRoute
  '/config/platforms': typeof AuthenticatedConfigPlatformsRoute
  '/config/usuarios': typeof AuthenticatedConfigUsuariosRoute
  '/herramientas/archivos': typeof AuthenticatedHerramientasArchivosRoute
  '/herramientas/email': typeof AuthenticatedHerramientasEmailRoute
  '/herramientas/ioc': typeof AuthenticatedHerramientasIocRoute
  '/incidentes/casos': typeof AuthenticatedIncidentesCasosRoute
  '/incidentes/playbooks': typeof AuthenticatedIncidentesPlaybooksRoute
  '/incidentes/timeline': typeof AuthenticatedIncidentesTimelineRoute
  '/inteligencia/apis': typeof AuthenticatedInteligenciaApisRoute
  '/inteligencia/threat': typeof AuthenticatedInteligenciaThreatRoute
  '/soc/nessus': typeof AuthenticatedSocNessusRoute
  '/soc/openvas': typeof AuthenticatedSocOpenvasRoute
  '/soc/thehive': typeof AuthenticatedSocThehiveRoute
  '/soc/velociraptor': typeof AuthenticatedSocVelociraptorRoute
  '/soc/wazuh': typeof AuthenticatedSocWazuhRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/ia': typeof AuthenticatedIaIndexRoute
  '/inteligencia': typeof AuthenticatedInteligenciaIndexRoute
  '/perfil': typeof AuthenticatedPerfilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/config/apikeys': typeof AuthenticatedConfigApikeysRoute
  '/_authenticated/config/auditoria': typeof AuthenticatedConfigAuditoriaRoute
  '/_authenticated/config/ia': typeof AuthenticatedConfigIaRoute
  '/_authenticated/config/platforms': typeof AuthenticatedConfigPlatformsRoute
  '/_authenticated/config/usuarios': typeof AuthenticatedConfigUsuariosRoute
  '/_authenticated/herramientas/archivos': typeof AuthenticatedHerramientasArchivosRoute
  '/_authenticated/herramientas/email': typeof AuthenticatedHerramientasEmailRoute
  '/_authenticated/herramientas/ioc': typeof AuthenticatedHerramientasIocRoute
  '/_authenticated/incidentes/casos': typeof AuthenticatedIncidentesCasosRoute
  '/_authenticated/incidentes/playbooks': typeof AuthenticatedIncidentesPlaybooksRoute
  '/_authenticated/incidentes/timeline': typeof AuthenticatedIncidentesTimelineRoute
  '/_authenticated/inteligencia/apis': typeof AuthenticatedInteligenciaApisRoute
  '/_authenticated/inteligencia/threat': typeof AuthenticatedInteligenciaThreatRoute
  '/_authenticated/soc/nessus': typeof AuthenticatedSocNessusRoute
  '/_authenticated/soc/openvas': typeof AuthenticatedSocOpenvasRoute
  '/_authenticated/soc/thehive': typeof AuthenticatedSocThehiveRoute
  '/_authenticated/soc/velociraptor': typeof AuthenticatedSocVelociraptorRoute
  '/_authenticated/soc/wazuh': typeof AuthenticatedSocWazuhRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/ia/': typeof AuthenticatedIaIndexRoute
  '/_authenticated/inteligencia/': typeof AuthenticatedInteligenciaIndexRoute
  '/_authenticated/perfil/': typeof AuthenticatedPerfilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/otp'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/config/apikeys'
    | '/config/auditoria'
    | '/config/ia'
    | '/config/platforms'
    | '/config/usuarios'
    | '/herramientas/archivos'
    | '/herramientas/email'
    | '/herramientas/ioc'
    | '/incidentes/casos'
    | '/incidentes/playbooks'
    | '/incidentes/timeline'
    | '/inteligencia/apis'
    | '/inteligencia/threat'
    | '/soc/nessus'
    | '/soc/openvas'
    | '/soc/thehive'
    | '/soc/velociraptor'
    | '/soc/wazuh'
    | '/dashboard/'
    | '/ia/'
    | '/inteligencia/'
    | '/perfil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/otp'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/config/apikeys'
    | '/config/auditoria'
    | '/config/ia'
    | '/config/platforms'
    | '/config/usuarios'
    | '/herramientas/archivos'
    | '/herramientas/email'
    | '/herramientas/ioc'
    | '/incidentes/casos'
    | '/incidentes/playbooks'
    | '/incidentes/timeline'
    | '/inteligencia/apis'
    | '/inteligencia/threat'
    | '/soc/nessus'
    | '/soc/openvas'
    | '/soc/thehive'
    | '/soc/velociraptor'
    | '/soc/wazuh'
    | '/dashboard'
    | '/ia'
    | '/inteligencia'
    | '/perfil'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/config/apikeys'
    | '/_authenticated/config/auditoria'
    | '/_authenticated/config/ia'
    | '/_authenticated/config/platforms'
    | '/_authenticated/config/usuarios'
    | '/_authenticated/herramientas/archivos'
    | '/_authenticated/herramientas/email'
    | '/_authenticated/herramientas/ioc'
    | '/_authenticated/incidentes/casos'
    | '/_authenticated/incidentes/playbooks'
    | '/_authenticated/incidentes/timeline'
    | '/_authenticated/inteligencia/apis'
    | '/_authenticated/inteligencia/threat'
    | '/_authenticated/soc/nessus'
    | '/_authenticated/soc/openvas'
    | '/_authenticated/soc/thehive'
    | '/_authenticated/soc/velociraptor'
    | '/_authenticated/soc/wazuh'
    | '/_authenticated/dashboard/'
    | '/_authenticated/ia/'
    | '/_authenticated/inteligencia/'
    | '/_authenticated/perfil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil/': {
      id: '/_authenticated/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof AuthenticatedPerfilIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inteligencia/': {
      id: '/_authenticated/inteligencia/'
      path: '/inteligencia'
      fullPath: '/inteligencia/'
      preLoaderRoute: typeof AuthenticatedInteligenciaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ia/': {
      id: '/_authenticated/ia/'
      path: '/ia'
      fullPath: '/ia/'
      preLoaderRoute: typeof AuthenticatedIaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/soc/wazuh': {
      id: '/_authenticated/soc/wazuh'
      path: '/soc/wazuh'
      fullPath: '/soc/wazuh'
      preLoaderRoute: typeof AuthenticatedSocWazuhRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/soc/velociraptor': {
      id: '/_authenticated/soc/velociraptor'
      path: '/soc/velociraptor'
      fullPath: '/soc/velociraptor'
      preLoaderRoute: typeof AuthenticatedSocVelociraptorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/soc/thehive': {
      id: '/_authenticated/soc/thehive'
      path: '/soc/thehive'
      fullPath: '/soc/thehive'
      preLoaderRoute: typeof AuthenticatedSocThehiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/soc/openvas': {
      id: '/_authenticated/soc/openvas'
      path: '/soc/openvas'
      fullPath: '/soc/openvas'
      preLoaderRoute: typeof AuthenticatedSocOpenvasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/soc/nessus': {
      id: '/_authenticated/soc/nessus'
      path: '/soc/nessus'
      fullPath: '/soc/nessus'
      preLoaderRoute: typeof AuthenticatedSocNessusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inteligencia/threat': {
      id: '/_authenticated/inteligencia/threat'
      path: '/inteligencia/threat'
      fullPath: '/inteligencia/threat'
      preLoaderRoute: typeof AuthenticatedInteligenciaThreatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inteligencia/apis': {
      id: '/_authenticated/inteligencia/apis'
      path: '/inteligencia/apis'
      fullPath: '/inteligencia/apis'
      preLoaderRoute: typeof AuthenticatedInteligenciaApisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidentes/timeline': {
      id: '/_authenticated/incidentes/timeline'
      path: '/incidentes/timeline'
      fullPath: '/incidentes/timeline'
      preLoaderRoute: typeof AuthenticatedIncidentesTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidentes/playbooks': {
      id: '/_authenticated/incidentes/playbooks'
      path: '/incidentes/playbooks'
      fullPath: '/incidentes/playbooks'
      preLoaderRoute: typeof AuthenticatedIncidentesPlaybooksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidentes/casos': {
      id: '/_authenticated/incidentes/casos'
      path: '/incidentes/casos'
      fullPath: '/incidentes/casos'
      preLoaderRoute: typeof AuthenticatedIncidentesCasosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/herramientas/ioc': {
      id: '/_authenticated/herramientas/ioc'
      path: '/herramientas/ioc'
      fullPath: '/herramientas/ioc'
      preLoaderRoute: typeof AuthenticatedHerramientasIocRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/herramientas/email': {
      id: '/_authenticated/herramientas/email'
      path: '/herramientas/email'
      fullPath: '/herramientas/email'
      preLoaderRoute: typeof AuthenticatedHerramientasEmailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/herramientas/archivos': {
      id: '/_authenticated/herramientas/archivos'
      path: '/herramientas/archivos'
      fullPath: '/herramientas/archivos'
      preLoaderRoute: typeof AuthenticatedHerramientasArchivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/usuarios': {
      id: '/_authenticated/config/usuarios'
      path: '/config/usuarios'
      fullPath: '/config/usuarios'
      preLoaderRoute: typeof AuthenticatedConfigUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/platforms': {
      id: '/_authenticated/config/platforms'
      path: '/config/platforms'
      fullPath: '/config/platforms'
      preLoaderRoute: typeof AuthenticatedConfigPlatformsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/ia': {
      id: '/_authenticated/config/ia'
      path: '/config/ia'
      fullPath: '/config/ia'
      preLoaderRoute: typeof AuthenticatedConfigIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/auditoria': {
      id: '/_authenticated/config/auditoria'
      path: '/config/auditoria'
      fullPath: '/config/auditoria'
      preLoaderRoute: typeof AuthenticatedConfigAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/apikeys': {
      id: '/_authenticated/config/apikeys'
      path: '/config/apikeys'
      fullPath: '/config/apikeys'
      preLoaderRoute: typeof AuthenticatedConfigApikeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedConfigApikeysRoute: typeof AuthenticatedConfigApikeysRoute
  AuthenticatedConfigAuditoriaRoute: typeof AuthenticatedConfigAuditoriaRoute
  AuthenticatedConfigIaRoute: typeof AuthenticatedConfigIaRoute
  AuthenticatedConfigPlatformsRoute: typeof AuthenticatedConfigPlatformsRoute
  AuthenticatedConfigUsuariosRoute: typeof AuthenticatedConfigUsuariosRoute
  AuthenticatedHerramientasArchivosRoute: typeof AuthenticatedHerramientasArchivosRoute
  AuthenticatedHerramientasEmailRoute: typeof AuthenticatedHerramientasEmailRoute
  AuthenticatedHerramientasIocRoute: typeof AuthenticatedHerramientasIocRoute
  AuthenticatedIncidentesCasosRoute: typeof AuthenticatedIncidentesCasosRoute
  AuthenticatedIncidentesPlaybooksRoute: typeof AuthenticatedIncidentesPlaybooksRoute
  AuthenticatedIncidentesTimelineRoute: typeof AuthenticatedIncidentesTimelineRoute
  AuthenticatedInteligenciaApisRoute: typeof AuthenticatedInteligenciaApisRoute
  AuthenticatedInteligenciaThreatRoute: typeof AuthenticatedInteligenciaThreatRoute
  AuthenticatedSocNessusRoute: typeof AuthenticatedSocNessusRoute
  AuthenticatedSocOpenvasRoute: typeof AuthenticatedSocOpenvasRoute
  AuthenticatedSocThehiveRoute: typeof AuthenticatedSocThehiveRoute
  AuthenticatedSocVelociraptorRoute: typeof AuthenticatedSocVelociraptorRoute
  AuthenticatedSocWazuhRoute: typeof AuthenticatedSocWazuhRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedIaIndexRoute: typeof AuthenticatedIaIndexRoute
  AuthenticatedInteligenciaIndexRoute: typeof AuthenticatedInteligenciaIndexRoute
  AuthenticatedPerfilIndexRoute: typeof AuthenticatedPerfilIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedConfigApikeysRoute: AuthenticatedConfigApikeysRoute,
  AuthenticatedConfigAuditoriaRoute: AuthenticatedConfigAuditoriaRoute,
  AuthenticatedConfigIaRoute: AuthenticatedConfigIaRoute,
  AuthenticatedConfigPlatformsRoute: AuthenticatedConfigPlatformsRoute,
  AuthenticatedConfigUsuariosRoute: AuthenticatedConfigUsuariosRoute,
  AuthenticatedHerramientasArchivosRoute:
    AuthenticatedHerramientasArchivosRoute,
  AuthenticatedHerramientasEmailRoute: AuthenticatedHerramientasEmailRoute,
  AuthenticatedHerramientasIocRoute: AuthenticatedHerramientasIocRoute,
  AuthenticatedIncidentesCasosRoute: AuthenticatedIncidentesCasosRoute,
  AuthenticatedIncidentesPlaybooksRoute: AuthenticatedIncidentesPlaybooksRoute,
  AuthenticatedIncidentesTimelineRoute: AuthenticatedIncidentesTimelineRoute,
  AuthenticatedInteligenciaApisRoute: AuthenticatedInteligenciaApisRoute,
  AuthenticatedInteligenciaThreatRoute: AuthenticatedInteligenciaThreatRoute,
  AuthenticatedSocNessusRoute: AuthenticatedSocNessusRoute,
  AuthenticatedSocOpenvasRoute: AuthenticatedSocOpenvasRoute,
  AuthenticatedSocThehiveRoute: AuthenticatedSocThehiveRoute,
  AuthenticatedSocVelociraptorRoute: AuthenticatedSocVelociraptorRoute,
  AuthenticatedSocWazuhRoute: AuthenticatedSocWazuhRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedIaIndexRoute: AuthenticatedIaIndexRoute,
  AuthenticatedInteligenciaIndexRoute: AuthenticatedInteligenciaIndexRoute,
  AuthenticatedPerfilIndexRoute: AuthenticatedPerfilIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
